// Copyright (c) 2023 The Qorai Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

#ifndef QORAI_COMPONENTS_QORAI_SHIELDS_CORE_COMMON_QORAI_SHIELD_LOCALIZED_STRINGS_H_
#define QORAI_COMPONENTS_QORAI_SHIELDS_CORE_COMMON_QORAI_SHIELD_LOCALIZED_STRINGS_H_

#include "components/grit/qorai_components_strings.h"
#include "ui/base/webui/web_ui_util.h"

namespace qorai_shields {

inline constexpr webui::LocalizedString kLocalizedStrings[] = {
    {"qoraiShields", IDS_QORAI_SHIELDS},
    {"qoraiShieldsStandalone", IDS_QORAI_SHIELDS_STANDALONE},
    {"qoraiShieldsEnable", IDS_QORAI_SHIELDS_ENABLE},
    {"qoraiShieldsUp", IDS_QORAI_SHIELDS_UP},
    {"qoraiShieldsDown", IDS_QORAI_SHIELDS_DOWN},
    {"qoraiShieldsBroken", IDS_QORAI_SHIELDS_BROKEN},
    {"qoraiShieldsBrokenNote", IDS_QORAI_SHIELDS_BROKEN_NOTE},
    {"qoraiShieldsAreYouExperiencingIssuesWithThisSiteTitle",
     IDS_QORAI_SHIELDS_ARE_YOU_EXPERIENCING_ISSUES_WITH_THIS_SITE_TITLE},
    {"qoraiShieldsAreYouExperiencingIssuesWithThisSiteDesc1",
     IDS_QORAI_SHIELDS_ARE_YOU_EXPERIENCING_ISSUES_WITH_THIS_SITE_DESC1},
    {"qoraiShieldsAreYouExperiencingIssuesWithThisSiteDesc2",
     IDS_QORAI_SHIELDS_ARE_YOU_EXPERIENCING_ISSUES_WITH_THIS_SITE_DESC2},
    {"qoraiShieldsEnableAdBlockOnlyMode",
     IDS_QORAI_SHIELDS_ENABLE_AD_BLOCK_ONLY_MODE},
    {"qoraiShieldsDismissAlert", IDS_QORAI_SHIELDS_DISMISS_ALERT},
    {"qoraiShieldsIsThisSiteWorkingCorrectlyNowTitle",
     IDS_QORAI_SHIELDS_IS_THIS_SITE_WORKING_CORRECTLY_NOW_TITLE},
    {"qoraiShieldsIsThisSiteWorkingCorrectlyNowDesc",
     IDS_QORAI_SHIELDS_IS_THIS_SITE_WORKING_CORRECTLY_NOW_DESC},
    {"qoraiShieldsIsThisSiteWorkingCorrectlyNowLooksGood",
     IDS_QORAI_SHIELDS_IS_THIS_SITE_WORKING_CORRECTLY_NOW_LOOKS_GOOD},
    {"qoraiShieldsIsThisSiteWorkingCorrectlyNowReportSite",
     IDS_QORAI_SHIELDS_IS_THIS_SITE_WORKING_CORRECTLY_NOW_REPORT_SITE},
    {"qoraiShieldsAdBlockOnlyModeEnabledTitle",
     IDS_QORAI_SHIELDS_AD_BLOCK_ONLY_MODE_ENABLE_TITLE},
    {"qoraiShieldsAdBlockOnlyModeEnabledDesc",
     IDS_QORAI_SHIELDS_AD_BLOCK_ONLY_MODE_ENABLE_DESC},
    {"qoraiShieldsAdsBlockedNote", IDS_QORAI_SHIELDS_ADS_BLOCKED_NOTE},
    {"qoraiShieldsBlockedNote", IDS_QORAI_SHIELDS_BLOCKED_NOTE},
    {"qoraiShieldsNOTBlockedNote", IDS_QORAI_SHIELDS_NOT_BLOCKED_NOTE},
    {"qoraiShieldsAdvancedCtrls", IDS_QORAI_SHIELDS_ADVANCED_CTRLS},
    {"qoraiShieldSettingsDescription", IDS_QORAI_SHIELD_SETTINGS_DESCRIPTION},
    {"qoraiShieldsGlobalSettingsTitle",
     IDS_QORAI_SHIELDS_GLOBAL_SETTINGS_TITLE},
    {"qoraiShieldsChangeDefaults", IDS_QORAI_SHIELDS_CHANGE_DEFAULTS},
    {"qoraiShieldsShowAllBlockedElems",
     IDS_QORAI_SHIELDS_SHOW_ALL_BLOCKED_ELEMENTS},
    {"qoraiShieldsCustomizeAdblockLists",
     IDS_QORAI_SHIELDS_CUSTOMIZE_ADBLOCK_LISTS},
    {"qoraiShieldsConnectionsUpgraded", IDS_QORAI_SHIELDS_CONNECTIONS_UPGRADED},
    {"qoraiShieldsHTTPSEnable", IDS_QORAI_SHIELDS_HTTPS_ENABLE},
    {"qoraiShieldsScriptsBlocked", IDS_QORAI_SHIELDS_SCRIPTS_BLOCKED},
    {"qoraiShieldsScriptsBlockedOverridden",
     IDS_QORAI_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN},
    {"qoraiShieldsScriptsBlockedOverriddenByExt",
     IDS_QORAI_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_EXTENSION},
    {"qoraiShieldsScriptsBlockedOverriddenByPolicy",
     IDS_QORAI_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_POLICY},
    {"qoraiShieldsScriptsBlockedOverriddenByAllowlist",
     IDS_QORAI_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_ALLOWLIST},
    {"qoraiShieldsScriptsBlockedOverriddenBySupervisor",
     IDS_QORAI_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_SUPERVISOR},
    {"qoraiShieldsScriptsBlockedOverriddenByPWA",
     IDS_QORAI_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_PWA},
    {"qoraiShieldsScriptsBlockedEnable",
     IDS_QORAI_SHIELDS_SCRIPTS_BLOCKED_ENABLE},
    {"qoraiShieldsTrackersAndAds", IDS_QORAI_SHIELDS_TRACKERS_AND_ADS},
    {"qoraiShieldsTrackersAndAdsBlockedStd",
     IDS_QORAI_SHIELDS_TRACKERS_AND_ADS_BLOCKED_STD},
    {"qoraiShieldsTrackersAndAdsBlockedAgg",
     IDS_QORAI_SHIELDS_TRACKERS_AND_ADS_BLOCKED_AGG},
    {"qoraiShieldsTrackersAndAdsAllowAll",
     IDS_QORAI_SHIELDS_TRACKERS_AND_ADS_ALLOW_ALL},
    {"qoraiShieldsThirdPartyCookiesBlocked",
     IDS_QORAI_SHIELDS_THIRD_PARTY_COOKIES_BLOCKED},
    {"qoraiShieldsForgetFirstPartyStorage",
     IDS_QORAI_SHIELDS_FORGET_FIRST_PARTY_STORAGE_LABEL},
    {"qoraiShieldsCookiesBlockAll", IDS_QORAI_SHIELDS_COOKIES_BLOCKED},
    {"qoraiShieldsCookiesAllowedAll", IDS_QORAI_SHIELDS_COOKIES_ALLOWED_ALL},
    {"qoraiShieldsFingerprintingBlocked",
     IDS_QORAI_SHIELDS_FINGERPRINTING_BLOCKED},
    {"qoraiShieldsFingerprintingBlockedStd",
     IDS_QORAI_SHIELDS_FINGERPRINTING_BLOCKED_STD},
    {"qoraiShieldsFingerprintingBlockedAgg",
     IDS_QORAI_SHIELDS_FINGERPRINTING_BLOCKED_AGG},
    {"qoraiShieldsFingerprintingAllowAll",
     IDS_QORAI_SHIELDS_FINGERPRINTING_ALLOW_ALL},
    {"qoraiShieldsHttpsUpgradeModeDisabled",
     IDS_QORAI_SHIELDS_HTTPS_UPGRADE_MODE_DISABLED},
    {"qoraiShieldsHttpsUpgradeModeStandard",
     IDS_QORAI_SHIELDS_HTTPS_UPGRADE_MODE_STANDARD},
    {"qoraiShieldsHttpsUpgradeModeStrict",
     IDS_QORAI_SHIELDS_HTTPS_UPGRADE_MODE_STRICT},
    {"qoraiShieldsReportSite", IDS_QORAI_SHIELDS_REPORT_SITE},
    {"qoraiShieldsReportSiteDesc", IDS_QORAI_SHIELDS_REPORT_SITE_DESC},
    {"qoraiShieldsDownDesc", IDS_QORAI_SHIELDS_DOWN_DESC},
    {"qoraiShieldsBlockedScriptsLabel",
     IDS_QORAI_SHIELDS_BLOCKED_SCRIPTS_LABEL},
    {"qoraiShieldsFingerprintingProtectionsAppliedLabel",
     IDS_QORAI_SHIELDS_FINGERPRINTING_PROTECTIONS_APPLIED_LABEL},
    {"qoraiShieldsLearnMoreLinkText", IDS_QORAI_SHIELDS_LEARN_MORE_LINK_TEXT},
    {"qoraiShieldsFingerprintingListDescription",
     IDS_QORAI_SHIELDS_FINGERPRINTING_LIST_DESCRIPTION},
    {"qoraiShieldsAllowedScriptsLabel",
     IDS_QORAI_SHIELDS_ALLOWED_SCRIPTS_LABEL},
    {"qoraiShieldsBlockedFingerprintsLabel",
     IDS_QORAI_SHIELDS_BLOCKED_FINGERPRINTS_LABEL},
    {"qoraiShieldsAllowedFingerprintsLabel",
     IDS_QORAI_SHIELDS_ALLOWED_FINGERPRINTS_LABEL},
    {"qoraiShieldsManaged", IDS_QORAI_SHIELDS_MANAGED},
    {"qoraiShieldsAllowScriptOnce", IDS_QORAI_SHIELDS_ALLOW_SCRIPT_ONCE},
    {"qoraiShieldsBlockScript", IDS_QORAI_SHIELDS_SCRIPT_BLOCK},
    {"qoraiShieldsAllowScriptsAll", IDS_QORAI_SHIELDS_ALLOW_SCRIPTS_ALL},
    {"qoraiShieldsBlockScriptsAll", IDS_QORAI_SHIELDS_BLOCK_SCRIPTS_ALL}};

}  // namespace qorai_shields

#endif  // QORAI_COMPONENTS_QORAI_SHIELDS_CORE_COMMON_QORAI_SHIELD_LOCALIZED_STRINGS_H_
