/* Copyright (c) 2022 The Qorai Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "qorai/browser/themes/qorai_private_window_theme_supplier.h"

#include "qorai/browser/ui/color/qorai_color_mixer.h"
#include "qorai/browser/ui/tabs/qorai_tab_color_mixer.h"
#include "ui/color/color_provider_key.h"

QoraiPrivateWindowThemeSupplier::QoraiPrivateWindowThemeSupplier(
    bool private_window)
    : CustomThemeSupplier(ThemeType::kAutogenerated),
      for_private_window_(private_window) {}

QoraiPrivateWindowThemeSupplier::~QoraiPrivateWindowThemeSupplier() = default;

void QoraiPrivateWindowThemeSupplier::AddColorMixers(
    ui::ColorProvider* provider,
    const ui::ColorProviderKey& key) const {
  if (for_private_window_) {
    AddPrivateThemeColorMixer(provider, key);
    tabs::AddQoraiTabPrivateThemeColorMixer(provider, key);
  } else {
    AddTorThemeColorMixer(provider, key);
    tabs::AddQoraiTabTorThemeColorMixer(provider, key);
  }
  // Private/Tor uses same omnibox colors.
  AddQoraiOmniboxPrivateThemeColorMixer(provider, key);
}
